version: "3"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "443:443"
    networks:
      - app-network
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
